### ISSUE TITLE
( fertilized farmland ) increases crop output [[ bug ]]

### ISSUE THREAD

**Issue by pk-box** [blay09/FarmingForBlockheads#105]
https://i.imgur.com/WKAsYXb.gif

**Comment by BlayTheNinth** [comment]
What mod is adding the right-click harvesting?

**Comment by pk-box** [comment]
is All The Mods 6 park

**Comment by BlayTheNinth** [comment]
Is this still an issue? Likely this was a bad interaction with whatever mod was adding the right-click harvesting.
