### ISSUE TITLE
[1.16.4] Unable to change output count for existing items

### ISSUE THREAD

**Issue by jengendler** [blay09/FarmingForBlockheads#109]
I am trying to change the output count of Bone Meal from the default (1) to 16 in the MarketRegistry.json file but it doesn't appear to work. I can change the output count for custom items, so I tried adding it as a custom item, but it still shows as 1. I've attempted to change output count for items in Group Overrides and Entry Overrides but it doesn't take. Based on how I can do it with custom entries, here is how I have it coded:

    "minecraft:bone_meal": {
      "output": {
        "count": 16
      },

I don't get any errors, but it still shows as 1 count in game. If this is not possible, I would love for this to be a feature.

**Comment by BlayTheNinth** [comment]
The correct syntax for changing the count in entry overrides is:

```json
"minecraft:bone_meal": {
    "amount": 16
}
```

I've updated the example. Future versions will also allow "count" instead of "amount" to keep things consistent.

**Comment by jengendler** [comment]
Thank you for providing that syntax. Works beautifully.

I notice this feature does not work in the groupOverrides. Is that intentional? If so, tt would be great to have the ability to override the output amount for entire groups, to avoid having to target each one individually in the entryOverrides section. I can create a separate feature request for this if you prefer.
