### ISSUE TITLE
Oh Biomes You'll Go Support

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/FarmingForBlockheads#114]

**Comment by DedicatedMedic** [comment]
Hey I really love your mods and its exciting that you are considering adding compatibility for BYG! Not sure if this will save you any time but here is the datapack I've been using for the market and BYG
[FarmingForBlockheads-BYG.zip](https://github.com/blay09/FarmingForBlockheads/files/6408986/FarmingForBlockheads-BYG.zip)

**Comment by whiteeagle1985** [comment]
I'd love OBYG support for my future 1.19.2 modpack where I've chosen it over BOP.

@DedicatedMedic Would I have to unzip your datapack for it to work in my modpack in the meanwhile?
