### ISSUE TITLE
Can't seem to make it work

### ISSUE THREAD

**Issue by cygnusharvey** [blay09/FarmingForBlockheads#117]
I'm new to the making of datapacks, and I wanted to try and add some custom entries to this. I tried making it work in any way I saw, but nothing ever worked. I also downloaded another datapack that actually works, but I haven't managed to do so myself.

And I'm just confused as how should I make one. I tried modifying the market registry adding it the custom entries; adding custom .json files at the same folder; going into the data folder and adding either a single farmingforblockheads_compat folder with either a zip, or a custom .json file, or a folder and inside it the compat folder. Also tried to add them in datapacks, just in case, same with either one, two folders, one or a zip file.

So... I'm lost as to how make it actually work.

**Comment by BlayTheNinth** [comment]
- [Creating a data pack](https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack)
- [Inbuilt Examples](https://github.com/blay09/FarmingForBlockheads/tree/1.16.x/src/main/resources/data/farmingforblockheads/farmingforblockheads_compat)
- [Example JSON](https://gist.github.com/blay09/93a48d092d6dc570a64c81e1912dc4d0)

You can also just edit MarketRegistry.json directly, you only need data packs if you want to organize things better.
