### ISSUE TITLE
"amount" not registering?

### ISSUE THREAD

**Issue by foxanthony1** [blay09/FarmingForBlockheads#118]
This works great, except that every trade is one emerald for one item.

`{"customCategories": {
    "extra_goodies": {
      "name": "Playing with Trains! Extras!",
      "icon": {
        "item": "minecraft:creeper_head"
      }
    }
  },
  "customEntries": [
    {
      "output": {
        "item": "minecraft:fern",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:dead_bush",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:sea_pickle",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:brown_mushroom",
        "amount": 4
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:red_mushroom",
        "amount": 4
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:chorus_plant",
        "amount": 2
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:end_stone",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:glowstone",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:tube_coral_block",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:brain_coral_block",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:bubble_coral_block",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:fire_coral_block",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:horn_coral_block",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:tube_coral",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:bubble_coral",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:fire_coral",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:horn_coral",
        "amount": 16
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:tube_coral_fan",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:brain_coral_fan",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:bubble_coral_fan",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:fire_coral_fan",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:horn_coral_fan",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:bamboo",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:cocoa_beans",
        "amount": 4
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:nether_wart",
        "amount": 4
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:crimson_fungus",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:warped_fungus",
        "amount": 8
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    },
    {
      "output": {
        "item": "minecraft:creeper_head",
        "amount": 1
      },
      "payment": {
        "item": "minecraft:emerald"
      },
      "category": "extra_goodies"
    }

  ]
}
`

**Comment by BlayTheNinth** [comment]
Needs to be `count`, amount was only supported in entryOverrides and has since also been deprecated in favor of count.
