### ISSUE TITLE
[Suggestion] Add a Catalog Item Option

### ISSUE THREAD

**Issue by MokahTGS** [blay09/FarmingForBlockheads#12]
Would you consider adding a config option to turn off the trading stall and add a catalog item instead for activating the trade GUI?  This would give more options for mod packs.

**Comment by blay09** [comment]
I really like how the appearance of the merchant turned out, so I don't think I'll be adding a portable version anytime soon. 

I don't really see the need either, as in, what does a modpack gain from making you use an item instead of a block?

**Comment by BlayTheNinth** [comment]
Closing this due to above reasons.
