### ISSUE TITLE
Recipes not working on server

### ISSUE THREAD

**Issue by oiltanker** [blay09/FarmingForBlockheads#120]
Added mod to server mods list, recipes show in JEI, but when crafting in crafting bench no resulting item shows up.

**Comment by BlayTheNinth** [comment]
Are you able to `/give` the items via command or does that error too?

**Comment by oiltanker** [comment]
no, that works

**Comment by oiltanker** [comment]
in the logs there are no related recipe errors, but on the first start there was some block ID issues

**Comment by oiltanker** [comment]
I have tested it happens when you add subtract mods in the process of running the server

**Comment by oiltanker** [comment]
As I understood, forge is not particularly good with hot-swapping mods, even if they do not affect the world or existing blocks, so I guess there is no issue with the mod, just forge in general.
