### ISSUE TITLE
incompatibility with Malum

### ISSUE THREAD

**Issue by caligator** [blay09/FarmingForBlockheads#122]
when you boot a world, FFB throws an error stating that it has a registry error

"Expected item to be an item. was unknown string 'malum_runewood_sapling'"
can not find anything to fix this on FFB's end.

mod link: https://www.curseforge.com/minecraft/mc-mods/malum

cant find the registry that FFB seems to autogenerate and it doesnt like me trying to use the override to disable the malum sapling

**Comment by BlayTheNinth** [comment]
Farming for Blockheads doesn't seem to have any inbuilt Malum compatibility, probably some other mod, a datapack or MarketRegistry.json is adding it

**Comment by drakray** [comment]
I came to talk about that, but found the issue:
it's a typo in the malum jar, under data/malum/farmingforblockheads_compat/sapling.json, should be malum:runewood_sapling
