### ISSUE TITLE
1.16.5 Datapack to add  additional modded items to the market

### ISSUE THREAD

**Issue by seanimusprime** [blay09/FarmingForBlockheads#125]
I couldn't really find any datapacks that people have made to add more items to the Market, so I decided to give it a go myself.

This datapack contains most, or all, of the soil, fertilizer, flowers, saplings, seeds, berries, and mushrooms from the following mods:
- BetterEnd Reforged
- BetterNether Reforged
- Buzzier Bees
- Cinderscapes
- Create
- Endergetic Expansion
- Farmer's Delight
- Minecolonies
- Minecraft Earth Mod
- Nether's Delight
- Outer End
- Quark
- Supplementaries
- The Abyss 2
- Tropicraft
- Twilight Forest

Edit:
Here is an updated version of the datapack where everything is separated by mod and type, allowing you to easily disable the mods and items you might not want.

[farmingforblockheads_shopexpansion.zip](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/7268892/farmingforblockheads_shopexpansion.zip)

**Comment by BlayTheNinth** [comment]
Thanks for the submission, I've added it in 1.17+ (but changed a few to be disabled by default)

**Comment by bengrebe** [comment]
Whenever I try to add a new json file into this datapack with croptopia seed entries, it gets rid of the normal entries that are in this datapack. Is it possible to have both the entries in this datapack, as well as my own custom entries?
