### ISSUE TITLE
JEI is not populated until joining a singleplayer world

### ISSUE THREAD

**Issue by drakray** [blay09/FarmingForBlockheads#126]
When connecting to a server, directly after opening MC, using JEI, trades added in MarketRegistry.json are not visible.
If I open a single player world, quit, then go to the server, trades are visible.

Client and server have the same modList/config.
JSON is using groupOverrides, customCategories and customEntries

MC 1.16.5
Forge 36.2.8
FfB 7.3.1
JEI 7.7.1.126
Bunch of other mods

Bug is not new, just never took the time to report it -_-'

**Comment by DemonMartin** [comment]
Bug is already over a year old, planning to fix this?

**Comment by BlayTheNinth** [comment]
Blocked by #201

**Comment by drakray** [comment]
I saw the new update thank you :D
Will the fix be ported to 1.20.1?

**Comment by BlayTheNinth** [comment]
It involved a complete change of how market items are defined, so it cannot be backported as-is.
