### ISSUE TITLE
Marketplace crash when no trade is selected

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/FarmingForBlockheads#127]
### Minecraft Version

1.16

### Mod Loader

Forge

### Mod Loader Version

36.2.9

### Mod Version

FarmingForBlockheads_1.16.5-7.3.1

### Describe the Issue

When placing Emeralds in the Marketplace's trade UI without a trade selected, the game crashes. I managed to do it twice in a row on the public server.

Selecting a trade before putting the Emeralds works as intended.

Pastebin has a size limit so I cut the log to when JEI is done (there's a LOT of recipes error apparently) and the world is loaded.

Despite Immersive Backpacks being mentionned in the stack trace, taking it off did not change the crash.

### Logs

https://pastebin.com/XBiB6pL7

**Comment by NielsPilgaard** [comment]
Any chance this fix could be released? :)

**Comment by BlayTheNinth** [comment]
better late than never
