### ISSUE TITLE
Farming For Blockheads has failed to load correctly

### ISSUE THREAD

**Issue by emanuele246gi** [blay09/FarmingForBlockheads#128]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

38.0.16

### Mod Version

1.18-9.0.0

### Describe the Issue

Nothing explains better than a photo:
![Minecraft_ 1 18 09_12_2021 12_15_28](https://user-images.githubusercontent.com/61762317/145386763-4db6ecc6-7f26-457e-8b51-f64fcadeff6e.png)

### Logs

https://pastebin.com/2u4jCapy (crashlog)

### Do you use any performance-enhancing mods (e.g. OptiFine)?

FerriteCore and FPS Reducer

**Comment by BlayTheNinth** [comment]
Update Balm

**Comment by emanuele246gi** [comment]
Ok thanks!
