### ISSUE TITLE
Error after logging into world

### ISSUE THREAD

**Issue by ModernGamingWorld** [blay09/FarmingForBlockheads#135]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.6

### Mod Version

9.0.0

### Describe the Issue

![2021-12-22_01 15 10](https://user-images.githubusercontent.com/75923060/147051304-1fc97953-64fa-42d2-b4dd-7a1f0acff702.png)

Not sure if this is a Farming for Blockheads error or quark

**Comment by Vadim4135** [comment]
same problem

**Comment by ModernGamingWorld** [comment]
https://github.com/ModdingForBlockheads/FarmingForBlockheads/blob/1.18.x/forge/src/main/resources/data/farmingforblockheads/farmingforblockheads_compat/quark_soil.json

https://github.com/ModdingForBlockheads/FarmingForBlockheads/blob/1.18.x/forge/src/main/resources/data/farmingforblockheads/farmingforblockheads_compat/quark_mushroom.json

My guess is these need to be removed @blay09

**Comment by coldReactive** [comment]
Same problem.
