### ISSUE TITLE
API for access to MarketRegistry?

### ISSUE THREAD

**Issue by Wabbit0101** [blay09/FarmingForBlockheads#14]
Currently the various addons are all part of the blockheads mod itself. I'd like to add items from the RealWorld mod and my own crops mod. Can we have a formal API to do this (IMC? Java?). Stuff in the 'registry' packages seems the likely candidate but I'm not sure that is official. Also, multiple payment items (like for villager merchants...say 1 diamond + 2 emeralds)?

**Comment by blay09** [comment]
I'll get this in for the 1.11.2 port, for now it'll be safe to just use the internal classes because they won't be changing anymore in 1.10.2.

**Comment by blay09** [comment]
Added both Java and IMC API in the 1.12 version.
