### ISSUE TITLE
[Bug] Hopper cannot pull eggs from Chicken Nest.

### ISSUE THREAD

**Issue by RubyRezal** [blay09/FarmingForBlockheads#140]
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

0.12.12

### Mod Version

9.0.3

### Describe the Issue

Minecraft vanilla Hoppers are unable to pull collected eggs out of Chicken Nest.  Also, the Chicken Nest doesn't always seem to update its appearance properly when it collects eggs.

[2022-01-17_21-02-09_Farming for Blockheads - Chicken Nest Hopper Bug Test.zip](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/7885634/2022-01-17_21-02-09_Farming.for.Blockheads.-.Chicken.Nest.Hopper.Bug.Test.zip)

### Logs

https://mclo.gs/om3aZHM

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Tested in a clean sandbox instance with common libraries loaded.

**Comment by TheTennessee** [comment]
Ditto to the above. We have the same issue on our server.
