### ISSUE TITLE
1.18.1 - Registry errors with Malum

### ISSUE THREAD

**Issue by Elrol** [blay09/FarmingForBlockheads#142]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.59

### Mod Version

9.0.3

### Describe the Issue

When I log in to a world, a message shows up that states:

"There were registry errors in the FarmingForBlockheads market data. See the log for full details.
- Expected item to be an item, was unknown string 'malum:soulstone'"

To add on to that, in game I can't find 'malum:soulstone' however there is 'malum:soulstone_ore'

The log file was too large for pastebin so I attached it here instead:
[latest.log](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/7955740/latest.log)

### Logs

Attached above

### Do you use any performance-enhancing mods (e.g. OptiFine)?

N/A

**Comment by BlayTheNinth** [comment]
The entry is added on Malum's side, so it has to be fixed there: https://github.com/SammySemicolon/Malum-Mod/blob/1.18.1/src/main/resources/data/malum/farmingforblockheads_compat/saplings.json
