### ISSUE TITLE
Can't configure (1.12.2)

### ISSUE THREAD

**Issue by CircusSeal** [blay09/FarmingForBlockheads#143]
I'm trying to enable purchasing of vanilla flowers, but I can't change any of the settings. Here is a screenshot of where it takes me:

![Screenshot_20220201_103842](https://user-images.githubusercontent.com/58666765/152030194-59c13a37-26b4-4ad9-a769-bbdc5f728a7e.png)

I can highlight the options and everything, but it's not letting me change them. I also tried going into the in-game configuration menu, but I couldn't find anything in there about allowing the markets to sell flowers.

**Comment by BlayTheNinth** [comment]
Use a text editor instead of opening the JSON in your browser

**Comment by CircusSeal** [comment]
Ohhh, okay! It worked! Thank you very much! :)
