### ISSUE TITLE
Log warning: Called deprecated GlobalEntityTypeAttributes#put, use EntityAttributeCreationEvent

### ISSUE THREAD

**Issue by DocterDum** [blay09/FarmingForBlockheads#145]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.26

### Mod Version

7.3.1

### Describe the Issue

Farming for Blockheads is causing a warning on launch:
[12Feb2022 12:25:40.203] [Render thread/WARN] [net.minecraftforge.common.ForgeHooks/]: Called deprecated GlobalEntityTypeAttributes#put for farmingforblockheads:merchant, use EntityAttributeCreationEvent instead.

This occurs with only forge and Farming For Blockheads installed.

[latest.log](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/8052453/latest.log)

### Logs

Logs attached in description

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No, this occurs with only Forge and Farming For Blockheads

**Comment by BlayTheNinth** [comment]
Releases for newer Minecraft versions already use the new event.
