### ISSUE TITLE
Crash on load with Forge 40.0.18

### ISSUE THREAD

**Issue by iosgoodch** [blay09/FarmingForBlockheads#146]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.0.18

### Mod Version

farmingforblockheads-forge-1.18.2-10.0.0

### Describe the Issue

The FFB mod causes Minecraft to crash on load with Forge 40.0.18 installed.

### Logs

https://pastebin.com/YxGcj33c

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No performance-enhancing mods are installed.

**Comment by EldrinFal** [comment]
I'm having the same issue.  Using JAVA 18 and Optifine.  Mod works fine on MC 1.18.1 using an older Forge version.
[crash-2022-03-19_22.50.05-fml.txt](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/8310684/crash-2022-03-19_22.50.05-fml.txt)

**Comment by kwpugh** [comment]
VeggieWay runs fine for me without FFB installed.

**Comment by SzczepanskaAleks** [comment]
I changed version of the Forge to 4.0.17 and it works with Minecraft 1.18.2 and Farming for Blockheads if it helps someone.

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm & Farming for Blockheads

**Comment by iosgoodch** [comment]
Confirmed as fixed. Thank you!
