### ISSUE TITLE
java.lang.NullPointerException: Rendering screen

### ISSUE THREAD

**Issue by Snownee** [blay09/FarmingForBlockheads#153]
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

36.2.29

### Mod Version

7.3.1

### Describe the Issue

See crash report

### Logs

https://pastebin.com/uvvNrpeW

**Comment by BlayTheNinth** [comment]
Duplicate of #127 but needs backporting to 1.16
