### ISSUE TITLE
Shift click a trade in the market to automatically insert currency

### ISSUE THREAD

**Issue by TheDeviantCrafter** [blay09/FarmingForBlockheads#162]
Vanilla villagers have a feature where shift clicking a trade will move any emeralds from your inventory to the input slot. I would like to see something similar in the market. Since the market is often used for buying a single crop, it may be better to move only enough currency for one trade instead of a full stack.

**Comment by BlayTheNinth** [comment]
Clicking an entry now attempts to put one item into the payment slot, and shift-clicking an item attempts to put a full stack into the payment slot.
