### ISSUE TITLE
Allow Tags support for Default Payments in Market for 1.16.5 and above

### ISSUE THREAD

**Issue by ModernGamingWorld** [blay09/FarmingForBlockheads#165]
I am currently having this problem in 1.16.5 Plus and noticed I can't seem to use tags as Default Payments.

The reason why I think this would be a great feature

1. To Add Mod Support to the Market Default Payments to allow us Modpack Creators to have a better way to allow end users to use say one of the same items from Multiply mods
2. Allow more customizable ability to the market itself, Just adding a basic one item as a payment can be a real pain if you have mods that add more of said item.

**Comment by BlayTheNinth** [comment]
Duplicate of #84
