### ISSUE TITLE
OvenRenderer Crash on latest 1.12.2 version

### ISSUE THREAD

**Issue by JakeThatDog** [blay09/FarmingForBlockheads#167]
Trying to configure a custom modpack for a server's SMP I am a part of, and I can't seem to figure out a crash I'm getting with Cooking for Blockheads before the game is finished loading
[log.txt](https://github.com/ModdingForBlockheads/FarmingForBlockheads/files/9435927/log.txt)

**Comment by BlayTheNinth** [comment]
Scrolling through the log shows all kinds of errors loading classes from all kinds of mods. Something is very broken with your instance.
