### ISSUE TITLE
Caught Error from mod plugin 

### ISSUE THREAD

**Issue by Zelioth** [blay09/FarmingForBlockheads#168]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

43.1.25

### Mod Version

11.1.0

### Describe the Issue

Going through my custom mod pack and picking out issues while loading, creating single player world, and running the server environment with multiple people online I wanted to report the few issues I'm finding to help make the mod a little better. This could be affecting things in game but I myself wouldn't be able to pinpoint it directly so i wanted to report it here. 

 of this log from a single player creation it appears it encounters some error with JEI. I'm not sure if this error is the mod or JEI. 

Friends United Mod Pack with public server : https://www.curseforge.com/minecraft/modpacks/friends-united

### Logs

https://pastebin.com/C0VNhjRY

### Do you use any performance-enhancing mods (e.g. OptiFine)?

no

**Comment by BlayTheNinth** [comment]
There's nothing in the log that indicates this is related to Farming for Blockheads
