### ISSUE TITLE
Feeding Trough not feeding Mooshrooms

### ISSUE THREAD

**Issue by maidlll** [blay09/FarmingForBlockheads#169]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

43.1.38

### Mod Version

11.1.0

### Describe the Issue

Mooshrooms are not being fed by the feeding trough, works fine with sheep and normal cows(only ones ive tested so far) 

Playing the ATM 8 modpack if this has anything to do with it.

**Comment by BlayTheNinth** [comment]
Cannot reproduce, mooshrooms are fed with wheat just fine for me. Did you have at least two mooshrooms nearby?
