### ISSUE TITLE
Feeding trough not feeding correctly

### ISSUE THREAD

**Issue by SivartMcDorf** [blay09/FarmingForBlockheads#171]
### Minecraft Version

1.19.x

### Mod Loader

Forge

### Mod Loader Version

n/a

### Mod Version

current

### Describe the Issue

when feeding chocobos from chococraft no matter what when feeding golden chocobos with golden gyshals it produces golden chocobos.  But currently they produce yellow chocobos as if it were regular gyshals.  The two are two different items but something is off in the way it is feeding them when I had feed them it works great.

**Comment by BlayTheNinth** [comment]
This isn't something I can easily fix without adding very specific (and implementation-dependent) support for the golden gyshal handling, but I've created an event that fires when the feeding trough feeds, allowing other mods to override the handling. This could be used by an addon mod or Chococraft to initiate their custom handling.
