### ISSUE TITLE
Harvesters.. I know, I know...

### ISSUE THREAD

**Issue by fallenhunter1** [blay09/FarmingForBlockheads#172]
Yes, Thermal Cultivation, has a good set. As does many other mods. However, Thermal is the only one I am aware of with a working fruit picker. Be nice to see another option to that single one. No idea if this is within the scope of this mods roadmap. But This mod seems the most likely to include it. 

Would not require pipes, power gen, etc, that is all covered with other mods, but if you want it to work stand alone, just include a furnace fuel slot. Piping in Power or using fuel should not be that difficult.

**Comment by whiteeagle1985** [comment]
For tree crops I generally go with Botany Pots myself.

**Comment by BlayTheNinth** [comment]
Any kind of magic tech automation I don't really see in the scope of this mod. Farming for Blockheads is more so following Cooking for Blockheads' principle of having only a few utility blocks that enhance manual labor or complement other mods. Moving this to Discussions for now.
