### ISSUE TITLE
Fertilized farmland not all accounted for

### ISSUE THREAD

**Issue by NightOps007** [blay09/FarmingForBlockheads#186]
The variants of the fertilized farmland I can see in JEI is not all possible combinations; I got:
green, red, yellow, green&yellow, red&yellow
Missing(please add):
green&red, green&red&yellow

Increases crop output(green)
Speeds up growth(red)
Prevents trampling(yellow)

**Comment by BlayTheNinth** [comment]
Those combinations aren't possible which is why they do not show up. You can only apply either green or red fertilizer at once.
