### ISSUE TITLE
 The chicken coop is too weak.

### ISSUE THREAD

**Issue by RNT7890EX** [blay09/FarmingForBlockheads#189]
What I want to say here is that the chicken coop is too useless. It's even better for me to pick up the materials myself. The capacity of the hay bales is so small that it's not worth it. So I want to ask, what's the point of making this? Please strengthen it for me Or you could consider allowing customization.

**Comment by chocolatechipcats** [comment]
You can put it on top of a hopper to dump its contents into a chest.
