### ISSUE TITLE
Random Crashs with MouseTweaks update

### ISSUE THREAD

**Issue by Cazadorsniper** [blay09/FarmingForBlockheads#2]
MouseTweaks update 2.7.3 seems to be incompatible with Farming for Blockheads

crash: https://gist.github.com/Cazadorsniper/e01b72a294913323390ca7bce377f93a

I believe its because of an api change.

**Comment by blay09** [comment]
Mouse Tweaks broke its API and is planning on getting it fixed for the next version.

https://bitbucket.org/YaLTeR/mouse-tweaks/issues/6/noclassdeffounderror-error-upon-accessing

**Comment by blay09** [comment]
Should be fixed on MouseTweaks 2.8.
