### ISSUE TITLE
[Sponge] Merchant dies on impact

### ISSUE THREAD

**Issue by Liiw** [blay09/FarmingForBlockheads#20]
Hello! 

I am playing on a 1.10.2 spongeforge server with numerous other mods. Although it does not affect the functionality of the market block, every time someone places the market down, the villager, who should fall next to it, falls to his death. Could that be a Sponge issue?

**Comment by BlayTheNinth** [comment]
It's not happening with Forge by itself, so yes, probably a Sponge issue that needs to be fixed by them.

**Comment by Liiw** [comment]
I see, thanks for the reply! I will close this issue now.
