### ISSUE TITLE
Attempted to Register Duplicate Handler

### ISSUE THREAD

**Issue by katubug** [blay09/FarmingForBlockheads#207]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Mod Version

14.0.2

### Balm Version

7.2.1

### Describe the Issue

So by default, the saplings from the mod Fruitful Fun are available in the Market. I wanted to prevent this, because you're meant to get them through cross-pollination and I didn't want to bypass that mechanic. I couldn't find a premade compatibility pack in the jar, so I made my own:
 
[fruitfulfun_saplings.json](https://github.com/TwelveIterationMods/FarmingForBlockheads/files/14284656/fruitfulfun_saplings.json) (it's not complete because I just wanted to test if it was working before I messed with it further).

That incomplete datapack (which I'm loading through KubeJS) has the intended effect of making all Fruitful Fun saplings unavailable in the market. However, I receive this error in my chat log: https://i.imgur.com/b3Rtf46.png

It sounds like there's more than one datapack touching these saplings, but I'm not sure where the other one is or how to work with this. Thanks in advance for your time!

### Logs

https://gist.github.com/katubug/a952dbd4547a5f9ff9ca694ad81f45b9

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by BlayTheNinth** [comment]
Fruitful Fun includes its own datapack: https://github.com/Snownee/FruitfulFun/blob/1.20.1-fabric/src/main/resources/data/fruitfulfun/farmingforblockheads_compat/fruitfulfun_saplings.json

**Comment by BlayTheNinth** [comment]
You would have to use a groupOverride to disable `Fruitful Fun Saplings` and then name your custom group something else.

**Comment by katubug** [comment]
Ah, okay, thank you! I had no idea. I will just override their datapack and
have them disabled.
