### ISSUE TITLE
The market is unable to trade, even though I have emeralds

### ISSUE THREAD

**Issue by kkkakui** [blay09/FarmingForBlockheads#210]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

1.20.1

### Mod Version

14.0.2

### Balm Version

7.2.2

### Describe the Issue

I was making a modpack and when I used the market, I found that even with emeralds in the backpack, the transaction could not be completed. I didn't change any configuration files. Because there are so many mods, I don't know if one of them is blocking the transaction.

here the prints:
<img width="611" alt="{9F7B26AA-0203-4b87-B47E-7F71B14E1AFD}" src="https://github.com/TwelveIterationMods/FarmingForBlockheads/assets/154067471/eaac5fd7-00d1-4321-b4eb-3d46f2bde9d6">

Just this, thank you

**Comment by BlayTheNinth** [comment]
Needs a reproduction case and logs. Is something replacing the emerald item maybe?
