### ISSUE TITLE
Mod crashes on newer NeoForge builds

### ISSUE THREAD

**Issue by ModernGamingWorld** [blay09/FarmingForBlockheads#211]
### Minecraft Version

1.20.6

### Mod Loader

NeoForge

### Mod Loader Version

20.6.80

### Mod Version

neoforge-1.20.6-17.0.1

### Balm Version

10.0.2

### Describe the Issue

![2024-05-25_20 11 24](https://github.com/TwelveIterationMods/FarmingForBlockheads/assets/75923060/57155489-12d3-411b-853f-abaa31f03c4a)

**Comment by BlayTheNinth** [comment]
Fixed in latest Balm.
