### ISSUE TITLE
Bug related to Quark

### ISSUE THREAD

**Issue by Heitorzex** [blay09/FarmingForBlockheads#214]
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.3.0

### Mod Version

14.0.2

### Balm Version

7.3.4

### Describe the Issue

When playing on 1.20.1 forge with Quark, it's impossible to open/create a world, making it unplayable

**Comment by BlayTheNinth** [comment]
Please provide the full logs. You can find the logs in the `logs` directory of the client or server. Most of the time `latest.log` is the correct file (unless the crash or issue happened during an earlier run).

Logs can be uploaded here by dragging the file into the comment field, or you can post them on a site like https://gist.github.com/ or https://pastebin.com/. Make sure they are set to be `public` (or unlisted) and to `never expire`.
