### ISSUE TITLE
Market doesn't drop itself when broken in survival

### ISSUE THREAD

**Issue by MuteTiefling** [blay09/FarmingForBlockheads#216]
### Minecraft Version

1.21

### Mod Loader

NeoForge

### Mod Loader Version

21.0.42

### Mod Version

21.0.2

### Balm Version

21.0.11-all

### Describe the Issue

Market doesn't drop itself when broken in survival.
https://github.com/EnigmaticaModpacks/Enigmatica10/issues/13

**Comment by Gbergz** [comment]
The block still doesn't drop when harvested. Using `version 1.21-21.0.3`.

**Comment by BlayTheNinth** [comment]
Fixed again
