### ISSUE TITLE
Configurable Market Categories

### ISSUE THREAD

**Issue by Boolyman** [blay09/FarmingForBlockheads#22]
You give us the ability to disable certain modules of cold items... but not the tab at the side of the GUI that shows a picture of those items?  Like, if I disable seeds from being sold... there shouldnt be a seed tab still at the right of the GUI.  Is there a way you can add a config for us to specify an item to appear on the label of the tabs?

**Comment by Boolyman** [comment]
Oooo, reassigned.  Hoping to see this in the future :)

**Comment by BlayTheNinth** [comment]
For now, the category buttons will be hidden if they're empty. Proper custom categories will follow in 1.13 when I re-do the json format.
