### ISSUE TITLE
NBT support in MarketRegistry.json

### ISSUE THREAD

**Issue by kjarvi** [blay09/FarmingForBlockheads#23]
This may already be a thing, but I was hoping there would be a way to add items to sell that have custom NBT tags. I wanted to be able to trade both ways a bucket of honey for a bee from Forestry, both of which have custom NBT tags.

**Comment by BlayTheNinth** [comment]
This is currently only possible via the code / IMC API.

**Comment by BlayTheNinth** [comment]
Apparently I lied and this was supported from the beginning, but it wasn't actually respecting it for the payment items. The next version will fix that. NBT can be specified like so:

```
"minecraft:stick@{test:12}": "2*minecraft:emerald@{asdasd:555}"
```
