### ISSUE TITLE
Not feeding Buffalos (from Totemic )

### ISSUE THREAD

**Issue by flapee** [blay09/FarmingForBlockheads#32]
MC 1.12.2
FarmingForBlockheads_1.12-3.1.5

Modpack (SevTech Ages 3.0.6)

Thx
p

**Comment by BlayTheNinth** [comment]
I've just tried and it's feeding buffallos just fine for me. I need more information. Make sure they're close enough and be aware of the maximum limit of animals (that you can find in the config).
