### ISSUE TITLE
[Suggestion] More supported mods.

### ISSUE THREAD

**Issue by Mathew322** [blay09/FarmingForBlockheads#33]
FarmingForBlockheads is super helpful but it should support more mods, personally I'd suggest Biomes O' Plenty, Natura, and Terraqueous.

Biomes O' Plenty adds a great number of trees to the game, along with the massive Sacred Oak Tree.
Natura adds a number of berry bushes and crops that can be planted like seeds.
Terraqueous adds a handful of fruit trees, some small fruit bushes, and grape vines.

**Comment by BlayTheNinth** [comment]
Biomes O' Plenty and Natura are already supported (except for the berry bushes, I'll be adding defaults for them in the next version).

**Comment by Mathew322** [comment]
In 3.1.12?

I see the Natura options in the Market.json file but I don't see anything for Biomes O' Plenty, is there a line of code I can add or something?
