### ISSUE TITLE
NullPointerException when placing a Market with a null placer

### ISSUE THREAD

**Issue by Zekrom64** [blay09/FarmingForBlockheads#38]
A player on our server decided to put a Market block into a block placer from Cyclic which caused a NullPointerException. After following the stack trace I found that the issue was that Cyclic passes null for the placer that the Market uses to determine its direction. I initially reported this to the Cyclic developer (see https://github.com/PrinceOfAmber/Cyclic/issues/865), but they said that passing null is valid (command blocks pass null also) and to report it here.

**Comment by BlayTheNinth** [comment]
Fixed in latest Cyclic version.
