### ISSUE TITLE
]1.12.2 - 3.1.19] Green Fertilizer not increasing crop output

### ISSUE THREAD

**Issue by VallenFrostweaver** [blay09/FarmingForBlockheads#40]
I've tested on wheat and carrots with and without bonemeal and the green fertilizer seems no better than the vanilla. I've increased the value in the config from 1.0 to 4.0 to 20.0 and there was no change.

**Comment by VallenFrostweaver** [comment]
\o/
Cool. I wanted to do a Bit-by-Bit on this. Any idea when it will be ready?

**Comment by BlayTheNinth** [comment]
It was waiting on CurseForge approval, it's up now.

**Comment by VallenFrostweaver** [comment]
Thanks! Keep up the great work BTW. Love your mods.
