### ISSUE TITLE
Dupe Bug? w/ Tinkers Construct (techionally)

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [blay09/FarmingForBlockheads#48]
The Farming Station uses a villager as its merchant. Right.... The Issue is that when you place it it spawns one. That is a issue because if you place it next to a TiC smeltary, and make the villager fall into it with any molten metal in it, you're pretty much getting a dupe bug of Emerald. I know its not the intended purpose, but it should be noted.

Fixes?
1: Make the villager not actually a villager, aka another mob, maybe a zombie reskined. Since zombies dont melt, all it would do is give blood in the smeltary. Still not ideal but is better then duping emeralds. (To be fair it costs emeralds to trade and if you just dupe them back...)

2: Remove the villager. Its not really needed, and could be removed, since its not needed.

I would want these fixes so im not trying to get all the seeds
Meaning melting down the villagers into emeralds. Casting them out just to use them to get seeds.

Emeralds is meant to be a hard resource, not something you have **infinite** amount of.

**Comment by BlayTheNinth** [comment]
I just tried to reproduce this and I'm pretty sure I fixed this a long time ago already. When I melt down Merchants in a smeltery I just get blood. What version are you on?
