### ISSUE TITLE
Allow custom merchant texture by merchant name via resource packs

### ISSUE THREAD

**Issue by SirAron111** [blay09/FarmingForBlockheads#55]
I thought it would be fun if the name set in the config or the names etc would if they are player names have the skin show of that player like the player mobs mod or the player skin zombies mod do. It should be possible.

**Comment by BlayTheNinth** [comment]
IIRC villager skins don't match player skins so this wouldn't be as easy as just overriding the skin.

What I could probably do is make it try to use a texture from `farmingforblockheads/textures/entity/merchant/<name>.png` to allow modpack devs to supply their own skins to be loaded as a resource pack.

**Comment by fallenhunter1** [comment]
I like the idea, but understand there may be a code issue. Hope someone with some brains figures it out (which leaves me out).

**Comment by BlayTheNinth** [comment]
Farming for Blockheads will now attempt to use the texture located at `farmingforblockheads/textures/entity/merchant_<normalized_name>.png` where `normalized_name` is the name of the merchant in all-lowercase, and with all non-ASCII letters or digits and spaces replaced with an underscore, e.g. `emerald_muncher`.
