### ISSUE TITLE
Feeding Trough support for Animania

### ISSUE THREAD

**Issue by Sunconure11** [blay09/FarmingForBlockheads#57]
1. Animania compat. Would it be possible to add support here?
2. Haven't gotten around to playing around with this mod yet, but if they aren't natural spawns, why not have the villagers spawn in villages?

**Comment by BlayTheNinth** [comment]
What in Animania needs compat?

The merchants aren't supposed to spawn independently from the market block.

**Comment by Sunconure11** [comment]
Animania has it's own system of feeding animals and what not, for instance, as well as watering them.

**Comment by BlayTheNinth** [comment]
Apparently Animania has a feeding trough of its own which would probably solve this problem if it wasn't for the recipe collision #59

**Comment by BlayTheNinth** [comment]
Closing since Animania hasn't updated beyond 1.12
