### ISSUE TITLE
Feeding Trough not working

### ISSUE THREAD

**Issue by Zygus42** [blay09/FarmingForBlockheads#58]
FarmingForBlockheads_1.12.2-3.1.28
forge-1.12.2-14.23.5.2838-installer-win

I put the feeder into a pen with 8 chickens that I spawned and filled it with a stack of seeds, but they're completely uninterested in it.

[latest.log](https://github.com/blay09/FarmingForBlockheads/files/3451258/latest.log)

**Comment by Zero9o1o** [comment]
The feeding trough by default will stop breeding animals when there is 8 or more around, you can change this in the config by setting "Feeding Trough Max Animals" in the config file to a larger number.
You can also change it's searching range for the feeding.

**Comment by Zygus42** [comment]
Ah, good to know.
