### ISSUE TITLE
[1.14.4, Request] Configs

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/FarmingForBlockheads#62]
Hello o/

I would like to request that the entries in the Market are made configurable, as with prior versions of the mod.

#### Versions
FarmingForBlockheads_1.14.4-5.2.3

**Comment by BlayTheNinth** [comment]
Data packs are used to override or extend the market now, loading .json files from "farmingforblockheads_compat" in the data pack.

https://gist.github.com/blay09/93a48d092d6dc570a64c81e1912dc4d0

**Comment by BlayTheNinth** [comment]
I'll probably make it load from config/MarketRegistry.json additionally to make it easier.

**Comment by Wissi** [comment]
Great mod we love your work.

We have custom datapacks for several mods, yet I just can't get yours to work through a datapack.

Using your "Market Configuration Example (for Minecraft 1.14)" and aren't able to get the other "inbuilt groups" to show up.
```
Current inbuilt group names (that can be used for group overrides) For Vanilla:
- Vanilla Flowers
- Vanilla Mushrooms
- BiomesOPlenty Saplings
```
Or even create a custom entry.
Tried in different "Folder Structures" (as per Minecraft's Datapacks wiki) and will load and recognize as a datapack in game, but your mod will not show any changes.
Folder Structures I tried (in world datapack folder):
```
\data\farmingforblockheads_compat\example.json
\data\farmingforblockheads_compat\recipes\example.json
\data\farmingforblockheads_compat\loot_tables\example.json
\data\farmingforblockheads_compat\tags\functions\example.json
```
Is there a specific _folder structure_ your mod is looking for the datapack or a _specific name_ for the .json file?

Full datapack file content is [here](https://gist.github.com/Wissi/e7d2af98557353f02eac542b426acf03).

Thank you so much for your great work, looking forward to add it to our modpacks.

**Comment by Karaclysm119** [comment]
Has anybody managed to get datapcks to work for this, I think I've tried just about every logical possibilty here and all i can successfully do is make the market have no items by having the json file within the farmingforblockheads_compat folder.

**Comment by BlayTheNinth** [comment]
I had an error in the example json which was causing customCategories to fail loading + some missing error handling in the datapack loading. The latest version should be clearer about errors and I've also updated the [README](https://github.com/blay09/FarmingForBlockheads/blob/1.14.x/README.md#custom-market-entries) to include info on custom market data.

BiomesOPlenty support and SimpleFarming Support has been added (and can also act as an example for your own files, see https://github.com/blay09/FarmingForBlockheads/tree/1.14.x/src/main/resources/data/farmingforblockheads/farmingforblockheads_compat).

**Comment by halk6000** [comment]
hello i try add mods for this market.
but still dont know how exacly work adding custom trade. this table mayble help understend.
sadzonka[ dębu,świerku,brzozy,tropikalna,akacji,ciemnego dębu, wiśni]
Saro's fruid trees Mod[applesappling, orangesapling]
Simple Farming[AppleSapling,ApricotSapling,BananaSapling,cherrySapling,mangoSapling,oliveSapling,orangeSapling,pearSapling,plumSapling]
deeper and Darker[echosapling]
Biomes o'Plenty[pierwotnaSapling,kwitnącaSapling,cypressSapling,snowblossomSapling,TęczowabrzozowaSapling,jodłySapling,pineSapling,redmapleSapling,orangemapleSapling,yellowmapleSapling,sekwojowaSapling,mahoniowaSapling,jakarandowaSapling,palmowaSapling,wierzbowaSapling,martwaSapling,magicznaSapling,mrocznaSapling,piekielnaSapling,empyrealSapling]
Ars Nouveau[kaskadowesadzonkiarchwood,płonącedrzewkoarchwood,irytującedrzewkoArchwood,KwitnącedrzewkoArchwood]
Forbidden & Arcanus[AurumSapling]
Ars Elemental[FlashingArchwoodSapling]
Occultism[sadzonka dębu,otherworldsapling]
fruits Delight[pearsapling,hawberrysapling,lycheesapling,mangosapling,persimmonsapling,peachsaplingorangesapling,applesapling,mamgosteensapling,bayberrysapling,kiwiSapling,figSapling,durianseed,pineapplesapling]
