### ISSUE TITLE
1.14.4-5.3.0 - Empty Market

### ISSUE THREAD

**Issue by MisterShawn** [blay09/FarmingForBlockheads#66]
I wasn't sure if the market had to be configured first, or if there should be default entries.
Screenshot is from my server, but I tested in single player and both were empty.

https://i.imgur.com/Cfe1J0R.png

**Comment by BlayTheNinth** [comment]
Is there any errors printed in chat on joining the world?

**Comment by MisterShawn** [comment]
https://hastebin.com/abijoduhiq.css

None were printed in chat. Just in the console.

**Comment by MisterShawn** [comment]
Just noticed this one... https://hastebin.com/bupividifa.bash
