### ISSUE TITLE
Fertilizer on grass crashes

### ISSUE THREAD

**Issue by Asshall** [blay09/FarmingForBlockheads#67]
If you apply any of the 3 fertilizer without hoeing down the grass you get this crash report

https://pastebin.com//isshxvYa

Also when you apply yellow fertilizer you can grow grop without water. Is that intended ?

**Comment by BlayTheNinth** [comment]
What version was this on?

**Comment by Asshall** [comment]
Woops it was on 5.2.3... I guess the bug is long gone ^^ I'll close the issue :) Thank you for the quick answer ;)
