### ISSUE TITLE
Green fertilizer not increasing crop yield on wheat.

### ISSUE THREAD

**Issue by Jcewazhere** [blay09/FarmingForBlockheads#71]
It also doesn't increase the yield of any other plant.
To verify I planted 2 9X9 fields, one with green fertilizer one with no fertilizer. I waited till every plant was fully grown then broke the wheat with an empty hand. Both fields yielded 80 wheat exactly.
I repeated the test with Quark's right click to harvest functionality and got the same results.

I do have a few mods adding plants, but none should affect farming or crop yields.

**Comment by BlayTheNinth** [comment]
Missing Forge feature: https://github.com/MinecraftForge/MinecraftForge/pull/5871
