### ISSUE TITLE
Empty market place upon adding custom entries

### ISSUE THREAD

**Issue by CosmicRune** [blay09/FarmingForBlockheads#78]
Market becomes empty after I added custom entries in Market.json config file. But without custom entries, everything loads fine. I'm using 1.12.2 version.

![Screenshot_1](https://user-images.githubusercontent.com/59450840/73603314-75868980-4546-11ea-9783-0db107a6a44b.png)

**Comment by Skydragonsz** [comment]
IIRC there is a link to an example file on the readme.

https://gist.github.com/blay09/93a48d092d6dc570a64c81e1912dc4d0

**Comment by BlayTheNinth** [comment]
Errors loading the registry are printed in both chat and logs.

**Comment by CosmicRune** [comment]
> IIRC there is a link to an example file on the readme.
> 
> https://gist.github.com/blay09/93a48d092d6dc570a64c81e1912dc4d0

I already tried that and it didn't work, But I thought that link example is for datapack, and not Market.json file in the config folder?

**Comment by CosmicRune** [comment]
> Errors loading the registry are printed in both chat and logs.

Nothing showed up in the chat but here's my latest log.

[latest.log](https://github.com/blay09/FarmingForBlockheads/files/4143590/latest.log)

**Comment by BlayTheNinth** [comment]
`[22:46:33] [Client thread/ERROR]: Failed to load Market registry: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 52 column 2 path $.custom entries.minecraft:stone`

**Comment by CosmicRune** [comment]
How do I fix that error?

**Comment by BlayTheNinth** [comment]
Post your full market config, the screenshot is outdated since there's no mentioning of minecraft:stone in there, yet the error is complaining about it.

**Comment by CosmicRune** [comment]
{
  "defaults": {
    "__comment": "You can disable defaults by setting these to false. Do *NOT* try to add additional entries here. You can add additional entries in the custom section.",
    "Vanilla Seeds": true,
    "Vanilla Flowers": false,
    "Vanilla Mushrooms": false,
    "Vanilla Saplings": true,
    "Bonemeal": true,
    "Animal Eggs": false,
    "Pams Harvestcraft Saplings": true,
    "BiomesOPlenty Saplings": true,
    "Forestry Saplings": false,
    "BiomesOPlenty Sacred Oak Sapling": false,
    "Pams Harvestcraft Seeds": true
  },
  "defaults payment": {
    "__comment": "You can define custom payment items for the default entries here.",
    "Vanilla Seeds": "1*minecraft:emerald:0",
    "Vanilla Flowers": "1*minecraft:emerald:0",
    "Vanilla Mushrooms": "1*minecraft:emerald:0",
    "Vanilla Saplings": "1*minecraft:emerald:0",
    "Bonemeal": "1*minecraft:emerald:0",
    "Animal Eggs": "1*minecraft:emerald:0",
    "Pams Harvestcraft Saplings": "1*minecraft:emerald:0",
    "BiomesOPlenty Saplings": "1*minecraft:emerald:0",
    "Forestry Saplings": "2*minecraft:emerald:0",
    "BiomesOPlenty Sacred Oak Sapling": "1*minecraft:emerald:8",
    "Pams Harvestcraft Seeds": "1*minecraft:emerald:0"
  },
  "defaults amount": {
    "__comment": "You can define custom amounts for the default entries here.",
    "Vanilla Seeds": 1,
    "Vanilla Flowers": 1,
    "Vanilla Mushrooms": 1,
    "Vanilla Saplings": 1,
    "Bonemeal": 1,
    "Animal Eggs": 1,
    "Pams Harvestcraft Saplings": 1,
    "BiomesOPlenty Saplings": 1,
    "Forestry Saplings": 1,
    "BiomesOPlenty Sacred Oak Sapling": 1,
    "Pams Harvestcraft Seeds": 1
  },
  "defaults blacklist": [
    "examplemod:example_item"
  ],

"custom entries": {
"__comment": "You can define additional items to be sold by the Market here. Defaults can be overridden. Prefix with ! to blacklist instead.",
"examplemod:example_item": "2*minecraft:emerald",
"minecraft:stone": "2*minecraft:emerald",
}
}

**Comment by BlayTheNinth** [comment]
There's an extra comma at the end that shouldn't be there.

**Comment by CosmicRune** [comment]
Oh my god, thank you so much <3 It works now :)
