### ISSUE TITLE
Only the last line shows up in game

### ISSUE THREAD

**Issue by CosmicRune** [blay09/FarmingForBlockheads#80]
So in this config, only the last line shows up in game. When I remove cobblestone, dirt one shows up. And when I remove dirt one, the emerald ones show up. Only the last line shows up no matter what. Is it because, more than one "1*thermalfoundation:coin:64" can't exist? 

"custom entries": {
"__comment": "You can define additional items to be sold by the Market here. Defaults can be overridden. Prefix with ! to blacklist instead.",
"examplemod:example_item": "2*minecraft:emerald",
"1*thermalfoundation:coin:64": "1*minecraft:emerald",              
"1*thermalfoundation:coin:64": "64*minecraft:dirt:0",
"1*thermalfoundation:coin:64": "64*minecraft:cobblestone"
}
}

**Comment by Skydragonsz** [comment]
I would recommend something like https://jsonlint.com/ to validate JSON files.
Yours for example misses some things.

> Is it because, more than one "1*thermalfoundation:coin:64" can't exist?

Also you are not allowed to have keys with the same name.

**Comment by CosmicRune** [comment]
If you're talking about the star signs next to the numbers, they don't always show up for some reason when I copy/paste them here. 

Ah I see, I hope it's a feature in the future or something. It'd be nice to sell things.

**Comment by BlayTheNinth** [comment]
#17
