### ISSUE TITLE
Configs are not registered for 1.14+

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/FarmingForBlockheads#81]

**Comment by P-rox-y** [comment]
Is this post/bug in reference to the config files not showing up in the following server directories?

\Minecraft\world\serverconfig
\Minecraft\config\farmingforblockheads

Or this a separate issue I'm experiencing? 

![image](https://user-images.githubusercontent.com/37484979/75005817-3789d080-5435-11ea-9133-e1f6cde470e6.png)

**Comment by BlayTheNinth** [comment]
MarketRegistry.json being empty by default is normal - it's a convenience file allowing you to change the market trades without using a data pack. See the [README](https://github.com/blay09/FarmingForBlockheads/blob/1.15.x/README.md) for info on that.

This issue is related to the `farmingforblockheads-common.toml` and `farmingforblockheads-client.toml` not being created, which contain a few general options (like the names the merchants will take on).
