### ISSUE TITLE
Adding a Custom Entry blanked out the Market

### ISSUE THREAD

**Issue by llloyd4** [blay09/FarmingForBlockheads#82]
Farming for Blockheads ver - 1.12.2-3.1.28 on Minecraft 1.12.2 and forge 1.12.2-14.23.5.2847 

So... I wanted to add in compatibility with Mystical Agriculture so down at the bottom, as a test, I put 

  "custom entries": {
    "__comment": "You can define additional items to be sold by the Market here. Defaults can be overridden. Prefix with ! to blacklist instead.",
    "examplemod:example_item": "2*minecraft:emerald"
  "mystical_agriculture:blaze_seeds": "1*minecraft:emerald"
  }

And that make the market go blank, completely, nothing is now showing up. O.o I grabbed the meta name from the Mystical Agriculture config file. In one section of the MA config is says

seeds {
    I:abyssalnite_seeds=1
    I:adamantine_seeds=1
    I:aluminum_brass_seeds=1
    I:aluminum_seeds=1
    I:alumite_seeds=1
    I:amber_seeds=1
    I:apatite_seeds=1
    I:aquamarine_seeds=1
    I:aquarium_seeds=1
    I:ardite_seeds=1
    I:basalt_seeds=1
    I:basalz_seeds=1
    I:black_quartz_seeds=1
    I:blaze_seeds=1
 ...
and so on and ad naseum ... Not sure what I did wrong here but now I can't buy any seeds. O.o

**Comment by BlayTheNinth** [comment]
Missing commas after entries

**Comment by Skydragonsz** [comment]
It's also best to put your config/custom entry through a [json checker](https://jsonlint.com/)

**Comment by llloyd4** [comment]
Ok, I put a comma after "mystical_agriculture:blaze_seeds": "1*minecraft:emerald" , and the Json Checker said it's valid, but the market is still blank. O.o

**Comment by Zero9o1o** [comment]
Can you copy the file into a pastebin and link it for me

**Comment by llloyd4** [comment]
@Zero9o1o - https://pastebin.com/6SYBe6Fu

**Comment by Zero9o1o** [comment]
The json is invalid the comma goes on line 40 after the example, not the agricraft entry you added.

**Comment by llloyd4** [comment]
@Zero9o1o Ok, so the default .json is at fault, a default unmodified (pulled it from the StoneBound 2 mod pack /config file ) is 

  ],
  "custom entries": {
    "__comment": "You can define additional items to be sold by the Market here. Defaults can be overridden. Prefix with ! to blacklist instead.",
    "examplemod:example_item": "2*minecraft:emerald"
  }

No comma. Let me move the comma.

**Comment by llloyd4** [comment]
Alright, fixed, and with some back and forth mod config, save, reload MC, I got blaze seeds added. Unfortunately the oredic name didn't work, oh well, happy to get it working and now I got to add all the rest and tweak the prices. Cool! Thanks Zero! 

Oh! FYI to future people reading this, it's 

"mysticalagriculture:blaze_seeds": "1*minecraft:emerald"

Though that being a tier 3 I'm thinking, in the spirit of MA, making it 16 emeralds. It's 4 essence to make the next tier essence, 4 of the next tier to make the tier after... Hmm, that would be more than 16. I'll do the maths later. Thanks again. :D

**Comment by Zero9o1o** [comment]
so when you add entries in json you need to add a comma after the previous entry

**Comment by llloyd4** [comment]
@Zero9o1o Ah, ok. So comma after all but the last.

**Comment by Zero9o1o** [comment]
Yeah that is how it works

**Comment by llloyd4** [comment]
@Zero9o1o Cool! Thanks. Still learning Jsons. At most I've ever done was tweak existing entries. :D
