### ISSUE TITLE
I'm trying to make "XL food mod" food items as part of the trades. I am using 1.15. 

### ISSUE THREAD

**Issue by Adelinklol** [blay09/FarmingForBlockheads#83]
I've tried to customize the configuration to do this but it doesn't work. Is it possible and can you help?

**Comment by BlayTheNinth** [comment]
I can't help while I have less info than you have. What have you tried and what doesn't work? How does your registry config look?

**Comment by Adelinklol** [comment]
Well, I went to the config folder in farmingforblockheads and pasted this:
"itemGroup.xlfoodmod": "XL Food Mod",
    "block.xlfoodmod.rock_salt": "Rock Salt",
: "Vanilla Flower",... 
etc, etc with all the foods

Then this happened:
![2020-03-08_14 05 06](https://user-images.githubusercontent.com/61952864/76262880-f286dc00-6233-11ea-92de-75fd67903708.png)

**Comment by BlayTheNinth** [comment]
https://gist.github.com/blay09/93a48d092d6dc570a64c81e1912dc4d0

**Comment by Adelinklol** [comment]
Do I copy/paste that and put in the items from xl food mod?

**Comment by BlayTheNinth** [comment]
Yes. Check out the existing compats too: https://github.com/blay09/FarmingForBlockheads/tree/1.15.x/src/main/resources/data/farmingforblockheads/farmingforblockheads_compat

And make sure to use the item registry names (F3+H and hover item), not the localization keys.
