### ISSUE TITLE
Allow Tags to be used as payment / defaultPayment

### ISSUE THREAD

**Issue by Partonetrain** [blay09/FarmingForBlockheads#84]
Using 1.15.2-6.1.0, I am unable to set defaultPayment to a tag, for example:

```
"defaultPayment": {
      "tag": "minecraft:planks"
    },
```

results in an invalid file and `Parsing error loading Farming for Blockheads data file at ....` in the log. It would be nice to be able to use tags here

**Comment by Partonetrain** [comment]
That said, I'm not sure how it could show in the interface. Maybe "1x any minecraft:planks"?

**Comment by ClaudiusMinimus** [comment]
I was actually just searching the same, though I want to use: <tag:forge:ingots/copper>

**Comment by ClaudiusMinimus** [comment]
Thank you. I look forward to seeing this new feature!
