### ISSUE TITLE
[1.15.2] Issues with MarketRegistry.json

### ISSUE THREAD

**Issue by realTIMematrix** [blay09/FarmingForBlockheads#87]
Hi,

I'm using:

- Minecraft 1.15.2
- Forge 31.1.43
- FarmingForBlockheads_1.15.2-6.1.0.jar
- Biomes O' Plenty 1.15.2-10.0.0.353
- simplefarming-1.15.2-1.2.7.jar

I also create the following MarketRegistry.json

`{
"groupOverrides": 
    {
    "Vanilla Saplings": {"enabled":false},
    "Vanilla Seeds": {"enabled":false},
    "Bone Meal": {"enabled":false},
    "Vanilla Flowers": {"enabled":true},
    "Vanilla Mushrooms": {"enabled":true},
    "Animal Eggs": {"enabled":true},
    "BiomesOPlenty Saplings": {"enabled":false},
    "BiomesOPlenty Flowers": {"enabled":true},
    "SimpleFarming Saplings": {"enabled":false},
    "SimpleFarming Seeds": {"enabled":false}
    }
}`

What I hope was that every "enabledByDefault" = true was turned off and vice versa. But instead everthing keeps turned off. 

So i don't know how to enable e.g. Vanilla Flowers or BiomesOPlenty Flowers. 

What I'm doing wrong?

Also when I click one of the filters on the right side everything disappears instead of showing only the selected group

**Comment by ghost** [comment]
you can load the extra Flowers/BoPFlowers by using a datapack. I use the [globaldatapack-1.15.2-1.3](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack) mod

It creates a folder called `global_data_pack`, inside this folder create a folder called `my_datapack\data\farmingforblockheads\farmingforblockheads_compat\`

Open the FarmingForBlockheads mod.jar file using WinZip/WinRar. Navigate to the following folder `data\farmingforblockheads\farmingforblockheads_compat`

Extract the files you want to enable into the `global_data_pack\my_datapack\data\farmingforblockheads\farmingforblockheads_compat\`

Open the files using a text editor, and set Enabled to true, save the file, and run Minecraft
The datapack mod should auto load these data files and the extra items should appear in the market

**Comment by realTIMematrix** [comment]
> you can load the extra Flowers/BoPFlowers by using a datapack. I use the [globaldatapack-1.15.2-1.3](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack) mod
> 
> It creates a folder called `global_data_pack`, inside this folder create a folder called `my_datapack\data\farmingforblockheads\farmingforblockheads_compat\`
> 
> Open the FarmingForBlockheads mod.jar file using WinZip/WinRar. Navigate to the following folder `data\farmingforblockheads\farmingforblockheads_compat`
> 
> Extract the files you want to enable into the `global_data_pack\my_datapack\data\farmingforblockheads\farmingforblockheads_compat\`
> 
> Open the files using a text editor, and set Enabled to true, save the file, and run Minecraft
> The datapack mod should auto load these data files and the extra items should appear in the market

I know that I can create a datapack for everything, still using open loader from darkhax. What my topic is that the config file from this mod is not working correct which you can't really fix with a datapack (or you fix it with a datapack but why do you have a config file?). 

BlayTheNinth has included and option to override the default settings from this mod. And this feature is not working correct. It is working only if you include additional datapacks (that overwrites the internal things). In my opinion this makes no sense. 

For example: In his mod settings/code he has the option for the "vanilla saplings = true" and in the options you can turn this off. But the default setting/code is for "vanilla flowers = false" and you can set it to true but it turns this flowers not on which his override rule should do. So the groupOverride is not working correct. It can turn things off, but not on (if the default is true)

**Comment by realTIMematrix** [comment]
It works now as expected. Thank you <3
