### ISSUE TITLE
[1.15.2] Server crashing on launch

### ISSUE THREAD

**Issue by Gagtech** [blay09/FarmingForBlockheads#90]
Hello,

I'm running ATM5 1.21 and the server has been pretty unstable.

Modpack is using  FarmingForBlockheads_1.15.2-6.1.1

The crash log has been pointing to the Farming for Blockheads mod.

Here is the crashlog:

https://pastebin.com/KMCZVGPa

**Comment by Gagtech** [comment]
Looks like a conflict with Mystical Agriculture?

**Comment by BlayTheNinth** [comment]
No, for some reason it was loading the config for the fertilized farmland incorrectly. No idea why it only seems to happen on some environments.
