### ISSUE TITLE
Categories are missing new 1.15 items

### ISSUE THREAD

**Issue by Notme2222** [blay09/FarmingForBlockheads#93]
Using FarmingForBlockheads_1.15.2-6.1.2.jar
Wither rose is also not in the market but that may be intended.
Also side note that when I tried to add Lily of the valley manually it ended up in the "other" tab, despite my setting the category to vanilla_flowers

**Comment by Notme2222** [comment]
Also the spawn eggs lacks panda and bee.

**Comment by BlayTheNinth** [comment]
The category is called "farmingforblockheads:flowers" - this example worked for me:

```json
"customEntries": [
    {
      "output": {
        "item": "minecraft:stick"
      },
      "category": "farmingforblockheads:flowers"
    }
  ]
```
