### ISSUE TITLE
Cinnamon Sapling is shown twice when searching in the Market

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/FarmingForBlockheads#95]
### Version
- FarmingForBlockheads_1.12.2-3.1.28

### Issue
I was searching for a Cinnamon Sapling in the Farming for Blockheads Market, and it shows the Cinnamon Sapling twice.

![billede](https://user-images.githubusercontent.com/21295394/83348161-31579a00-a32a-11ea-9b8e-9f01cfc8a494.png)

Original issue: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1716

**Comment by BlayTheNinth** [comment]
Are you using other data packs or MarketRegistry.json to add things to the market? Harvestcraft 2 support was recently added natively, so if you still have a data pack adding it manually that could be the reason why you got them double. 

Testing locally, I can only get it to appear once.

**Comment by NielsPilgaard** [comment]
This is on 1.12, so Harvestcraft 1 and no datapacks :)
Here's the Market.json: https://gist.github.com/NillerMedDild/70414cdd7580c89948b7eda0899021cc

**Comment by BlayTheNinth** [comment]
Oops, missed that. 1.12 is dead for my mods now apart from gamebreaking crashes, and it looks like the issue resolved itself in the 1.15 port, so closing as wontfix, but thanks for the report

**Comment by NielsPilgaard** [comment]
Fair enough :)
