### ISSUE TITLE
1.15.2 - Everything costs 1 emerald despite datapack overrides

### ISSUE THREAD

**Issue by Partonetrain** [blay09/FarmingForBlockheads#96]
![image](https://user-images.githubusercontent.com/19861808/83903369-a0b2fc80-a723-11ea-98b3-97dfcc679421.png)

```
{
  "modId": "minecraft",
  "group": {
    "name": "Herding",
    "enabledByDefault": true,
    "defaultPayment": {
      "item": "jsonifycraft:gemoney",
	  "count": 8
    },
    "defaultCategory": "farmingforblockheads:other"
  },
  "customEntries": [
    {
      "output": "minecraft:saddle"
    },
	{
      "output": "minecraft:name_tag"
    },
	{
      "output": "minecraft:lead"
    },
	{
      "output": "minecraft:beehive"
    },
	{
      "output": "buzzierbees:honey_wand"
    },
	{
      "output": "buzzierbees:bee_bottle"
    }
  ]
}

```

Using FarmingForBlockheads_1.15.2-6.1.3 and Forge-31.2.3

**Comment by Partonetrain** [comment]
reverting to 6.1.2 fixes this. Also, why was "count" removed?

**Comment by BlayTheNinth** [comment]
Default Payments no longer working right has been fixed in the latest version. What "count" do you mean that was removed?

**Comment by Partonetrain** [comment]
Sorry, somehow everything costing one emerald made me think the Count component was removed entirely. Should've known that was just the default...
