### ISSUE TITLE
Farming For Blockheads 1.16.1-7.0.0 Client Crash

### ISSUE THREAD

**Issue by ClaudiusMinimus** [blay09/FarmingForBlockheads#97]
I just added your Blockheads mods to my 1.16.1 pack in development. When I run either one of them the client crashes. I believe it is likely due to an [issue with Storage Drawers (1.16.1-8.0.0), which I have already reported](https://github.com/jaquadro/StorageDrawers/issues/855). When I remove your mods, the pack runs fine.

Minecraft: 1.16.1
Forge: 32.0.44
Cooking For Blockheads 1.16.1-9.0.0
Farming For Blockheads 1.16.1-7.0.0

https://paste.ee/p/3xPl3

**Comment by BlayTheNinth** [comment]
Both Cooking for Blockheads and Farming For Blockheads require Forge 32.0.48 or higher.
